# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 203)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.btnGeraCNPJ = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGeraCNPJ.setFont(font)
        self.btnGeraCNPJ.setObjectName("btnGeraCNPJ")
        self.gridLayout.addWidget(self.btnGeraCNPJ, 1, 2, 1, 1)
        self.inputValidaCNPJ = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputValidaCNPJ.setFont(font)
        self.inputValidaCNPJ.setObjectName("inputValidaCNPJ")
        self.gridLayout.addWidget(self.inputValidaCNPJ, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnValidaCNPJ = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCNPJ.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnValidaCNPJ.setFont(font)
        self.btnValidaCNPJ.setObjectName("btnValidaCNPJ")
        self.gridLayout.addWidget(self.btnValidaCNPJ, 0, 2, 1, 1)
        self.inputRetorno = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.inputRetorno.setFont(font)
        self.inputRetorno.setReadOnly(True)
        self.inputRetorno.setObjectName("inputRetorno")
        self.gridLayout.addWidget(self.inputRetorno, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valida ou gera CPF"))
        self.label.setText(_translate("MainWindow", "Gerar CNPJ:"))
        self.btnGeraCNPJ.setText(_translate("MainWindow", "GERAR"))
        self.label_2.setText(_translate("MainWindow", "Validar CNPJ:"))
        self.btnValidaCNPJ.setText(_translate("MainWindow", "VALIDAR"))
